#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2024 Hanbee Choi
# SPDX-License-Identifier: BSD-3-Clause

import sys

for line in sys.stdin:
    suuji = line.strip()

    if suuji.isdigit():
        kazu = int(suuji)
        kekka = kazu * 10  # 10倍に変更
        print(kekka)
    else:
        print("正確な数値ではありません。")

